version: "3.8"

services:
  cially-bot:
    image: ghcr.io/cially/cially-bot:latest
    container_name: cially-bot
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - API_URL=http://cially-bot:3001
      - DEBUGGING=${BOT_DEBUGGING:-FALSE}
      - POCKETBASE_URL=http://pocketbase:8090
      - GUILD_COLLECTION=guilds
      - MESSAGE_COLLECTION=messages
      - INVITE_COLLECTION=invites
      - MEMBER_LEAVES_COLLECTION=member_leaves
      - MEMBER_JOINS_COLLECTION=member_joins
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - pocketbase
      - cially-web
    networks:
      - cially-network

  cially-web:
    image: ghcr.io/cially/cially-web:latest
    container_name: cially-web
    restart: unless-stopped
    environment:
      # Runtime environment variables
      - NEXT_PUBLIC_BOT_API_URL=http://cially-bot:3001
      - POCKETBASE_URL=http://pocketbase:8090
      - MESSAGE_COLLECTION=messages
      - INVITE_COLLECTION=invites
      - MEMBER_LEAVES_COLLECTION=member_leaves
      - MEMBER_JOINS_COLLECTION=member_joins
      - GUILDS_COLLECTION=guilds
    ports:
      - "3000:3000"
    depends_on:
      - pocketbase
    networks:
      - cially-network

  pocketbase:
    image: ghcr.io/keksiqc/pocketbase:0.26.6
    container_name: cially-pocketbase
    restart: unless-stopped
    volumes:
      - pocketbase-data:/pb/pb_data
    ports:
      - "8090:8090"
    networks:
      - cially-network

networks:
  cially-network:
    driver: bridge

volumes:
  pocketbase-data:
