packages:
  - cially-bot
  - cially-web

catalog:
  '@biomejs/biome': 2.0.0-beta.6
  '@discordjs/rest': ^2.5.0
  '@hookform/resolvers': ^5.1.1
  '@tailwindcss/postcss': ^4.1.10
  '@types/node': ^24.0.1
  '@types/react': 19.1.6
  '@types/react-dom': 19.1.6
  body-parser: ^2.2.0
  cfonts: ^3.3.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  colors: ^1.4.0
  cron: ^4.3.1
  discord-api-types: ^0.38.11
  discord.js: ^14.19.3
  dotenv: ^16.5.0
  express: ^5.1.0
  ky: ^1.8.1
  lucide: ^0.514.0
  lucide-react: ^0.514.0
  multer: ^2.0.1
  next: 15.3.3
  next-themes: ^0.4.6
  node-fetch: ^3.3.2
  pocketbase: ^0.26.1
  radix-ui: ^1.4.2
  react: 19.1.0
  react-dom: 19.1.0
  react-hook-form: ^7.57.0
  recharts: ^2.15.3
  simple-get: ^4.0.1
  sonner: ^2.0.5
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.10
  taze: ^19.1.0
  tw-animate-css: ^1.3.4
  typescript: ^5.8.3
  winston: ^3.17.0
  zod: ^3.25.64

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - sharp

syncInjectedDepsAfterScripts:
  - build
