packages:
  - cially-bot
  - cially-web
injectWorkspacePackages: true
onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - sharp
syncInjectedDepsAfterScripts:
  - build
catalog:
  "@biomejs/biome": 2.0.0-beta.6
  "@discordjs/rest": ^2.5.0
  "@hookform/resolvers": ^4.1.3
  "@radix-ui/react-alert-dialog": ^1.1.11
  "@radix-ui/react-avatar": ^1.1.10
  "@radix-ui/react-dialog": ^1.1.6
  "@radix-ui/react-label": ^2.1.7
  "@radix-ui/react-scroll-area": ^1.2.9
  "@radix-ui/react-separator": ^1.1.7
  "@radix-ui/react-slot": ^1.2.3
  "@radix-ui/react-tabs": ^1.1.12
  "@radix-ui/react-tooltip": ^1.2.7
  "@tailwindcss/postcss": ^4
  "@types/node": ^20.17.57
  "@types/react": 19.1.6
  "@types/react-dom": 19.1.6
  body-parser: ^2.2.0
  cfonts: ^3.3.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  colors: ^1.4.0
  cron: ^4.3.1
  discord-api-types: ^0.38.10
  discord.js: ^14.18.0
  dotenv: ^16.5.0
  express: ^5.1.0
  ky: ^1.8.1
  lucide: ^0.487.0
  lucide-react: ^0.484.0
  multer: ^2.0.0
  next: 15.3.3
  next-themes: ^0.4.6
  node-fetch: ^3.3.2
  react: 19.1.0
  react-dom: 19.1.0
  react-hook-form: ^7.57.0
  recharts: ^2.15.3
  simple-get: ^4.0.1
  sonner: ^2.0.5
  tailwind-merge: ^3.3.0
  tailwindcss: ^4.1.8
  taze: ^19.1.0
  tw-animate-css: ^1.3.3
  typescript: ^5.8.3
  winston: ^3.17.0
  zod: ^3.25.49
