name: CI

on:
  workflow_dispatch:
# push:
# pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: "2.0.0-beta.6"
      - name: Run Biome
        run: biome ci .
